---
services:
  db_north:
    image: postgres:13
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./etl_meltano/data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - db_north_data:/var/lib/postgresql/data
    networks:
      - meltano
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U northwind_user -d northwind"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_final:
    image: postgres:13
    environment:
      POSTGRES_DB: finalwind
      POSTGRES_USER: finalwind_user
      POSTGRES_PASSWORD: finalwindisblowing
    volumes:
      - db_final_data:/var/lib/postgresql/data
    networks:
      - meltano
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finalwind_user -d finalwind"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  meltano:
    image: meltano/meltano:latest-python3.10
    depends_on:
      db_north:
        condition: service_healthy
      db_final:
        condition: service_healthy
    volumes:
      - ./etl_meltano:/project
    networks:
      - meltano
    command: ["meltano", "--help"]

volumes:
  db_north_data:
  db_final_data:

networks:
  meltano:
    driver: bridge
